# Generated by Django 5.0 on 2024-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured',
        ),
    ]
